"""empty message

Revision ID: 0903b02c42a1
Revises: c83e922455e5
Create Date: 2022-11-11 14:38:21.667852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0903b02c42a1'
down_revision = 'c83e922455e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###
