"""empty message

Revision ID: 0ff73eb5d7e0
Revises: 0903b02c42a1
Create Date: 2022-11-11 16:08:20.284006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ff73eb5d7e0'
down_revision = '0903b02c42a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
