"""empty message

Revision ID: 31749f67d6a2
Revises: 5903c28779ac
Create Date: 2022-11-11 16:11:49.940248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31749f67d6a2'
down_revision = '5903c28779ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###
