"""empty message

Revision ID: 5903c28779ac
Revises: 94bb7c1b390c
Create Date: 2022-11-11 16:11:13.358564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5903c28779ac'
down_revision = '94bb7c1b390c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
