"""empty message

Revision ID: 8be2392a30d2
Revises: 31749f67d6a2
Create Date: 2022-11-11 16:15:44.476574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8be2392a30d2'
down_revision = '31749f67d6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
