"""empty message

Revision ID: 94bb7c1b390c
Revises: 0ff73eb5d7e0
Create Date: 2022-11-11 16:08:52.439992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bb7c1b390c'
down_revision = '0ff73eb5d7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ftp_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'ftp_address')
    # ### end Alembic commands ###
