"""empty message

Revision ID: 9e2c1fa16b77
Revises: c116ea170e61
Create Date: 2022-11-04 14:24:24.985851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e2c1fa16b77'
down_revision = 'c116ea170e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qand_a')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qand_a',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='qand_a_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['answer.question_id'], name='qand_a_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['question.user_id'], name='qand_a_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
