"""empty message

Revision ID: c83e922455e5
Revises: 9e2c1fa16b77
Create Date: 2022-11-05 09:21:51.623108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83e922455e5'
down_revision = '9e2c1fa16b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.drop_index('tel', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tel', 'user', ['tel'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
